# yaml-language-server: $schema=https://json.schemastore.org/golangci-lint.json
version: "1"

run:
  timeout: 5m
  relative-path-mode: gomod
  tests: false
  go: "1.24.10"
  allow-parallel-runners: true
  concurrency: 4
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - errcheck
    - typecheck
    - gosec
    - revive
    - misspell
    - gocritic
    - durationcheck
    - nilerr
    - noctx
    - prealloc
    - exportloopref
    - whitespace
  settings:
    revive:
      rules:
        - name: exported
        - name: error-naming
          arguments: []
    misspell:
      locale: US
    gocritic:
      enabled-tags: [diagnostic, performance, style]
      disabled-checks: [hugeParam]
    gosec:
      severity: medium
      confidence: medium

# ⬇️ goimports & gofumpt live under formatters in v2
formatters:
  enable:
    - goimports
    - gofumpt
  settings:
    goimports:
      # change to your module path from go.mod
      local-prefixes: 
        - github.com/ayush1452/password-vault-cli-project
    gofumpt:
      extra-rules: true
  exclusions:
    generated: strict

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true
  new: false
  whole-files: true
  fix: false

output:
  sort-order:
    - linter
    - file
  show-stats: true

severity:
  default: error
