# golangci-lint configuration file (v1.55.2)
# See https://golangci-lint.run/configuration/ for more information

# The 'version' field is required and must be a string
version: v1.55.2

linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - unused
    - gosec
    - errcheck
    - typecheck
    - goimports

run:
  timeout: 5m
  modules-download-mode: readonly
