# golangci-lint configuration
version: 1.0.0

run:
  timeout: 5m
  modules-download-mode: mod

linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - unused
    - gosec
    - errcheck
    - typecheck
    - goimports
